CREATE TABLE endpoint_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_endpoint_hit_timestamp ON endpoint_hit (timestamp);
CREATE INDEX idx_endpoint_hit_uri_timestamp ON endpoint_hit (uri, timestamp);
CREATE INDEX idx_endpoint_hit_app_uri_timestamp ON endpoint_hit (app, uri, timestamp);
